/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.jooq.tables.records;


import org.example.infrastructure.jooq.tables.Commodity;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommodityRecord extends UpdatableRecordImpl<CommodityRecord> implements Record5<String, String, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ecom-plat.commodity.commodity_id</code>.
     */
    public void setCommodityId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ecom-plat.commodity.commodity_id</code>.
     */
    public String getCommodityId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ecom-plat.commodity.commodity_name</code>.
     */
    public void setCommodityName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ecom-plat.commodity.commodity_name</code>.
     */
    public String getCommodityName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ecom-plat.commodity.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ecom-plat.commodity.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ecom-plat.commodity.price</code>.
     */
    public void setPrice(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ecom-plat.commodity.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ecom-plat.commodity.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ecom-plat.commodity.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Commodity.COMMODITY.COMMODITY_ID;
    }

    @Override
    public Field<String> field2() {
        return Commodity.COMMODITY.COMMODITY_NAME;
    }

    @Override
    public Field<String> field3() {
        return Commodity.COMMODITY.DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return Commodity.COMMODITY.PRICE;
    }

    @Override
    public Field<String> field5() {
        return Commodity.COMMODITY.IMG_URL;
    }

    @Override
    public String component1() {
        return getCommodityId();
    }

    @Override
    public String component2() {
        return getCommodityName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer component4() {
        return getPrice();
    }

    @Override
    public String component5() {
        return getImgUrl();
    }

    @Override
    public String value1() {
        return getCommodityId();
    }

    @Override
    public String value2() {
        return getCommodityName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Integer value4() {
        return getPrice();
    }

    @Override
    public String value5() {
        return getImgUrl();
    }

    @Override
    public CommodityRecord value1(String value) {
        setCommodityId(value);
        return this;
    }

    @Override
    public CommodityRecord value2(String value) {
        setCommodityName(value);
        return this;
    }

    @Override
    public CommodityRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CommodityRecord value4(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public CommodityRecord value5(String value) {
        setImgUrl(value);
        return this;
    }

    @Override
    public CommodityRecord values(String value1, String value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommodityRecord
     */
    public CommodityRecord() {
        super(Commodity.COMMODITY);
    }

    /**
     * Create a detached, initialised CommodityRecord
     */
    public CommodityRecord(String commodityId, String commodityName, String description, Integer price, String imgUrl) {
        super(Commodity.COMMODITY);

        setCommodityId(commodityId);
        setCommodityName(commodityName);
        setDescription(description);
        setPrice(price);
        setImgUrl(imgUrl);
    }
}
