/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.jooq;


import java.util.Arrays;
import java.util.List;

import org.example.infrastructure.jooq.tables.Commodity;
import org.example.infrastructure.jooq.tables.Promotion;
import org.example.infrastructure.jooq.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EcomPlat extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ecom-plat</code>
     */
    public static final EcomPlat ECOM_PLAT = new EcomPlat();

    /**
     * The table <code>ecom-plat.commodity</code>.
     */
    public final Commodity COMMODITY = Commodity.COMMODITY;

    /**
     * The table <code>ecom-plat.promotion</code>.
     */
    public final Promotion PROMOTION = Promotion.PROMOTION;

    /**
     * The table <code>ecom-plat.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private EcomPlat() {
        super("ecom-plat", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Commodity.COMMODITY,
            Promotion.PROMOTION,
            User.USER);
    }
}
