/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.jooq;


import org.example.infrastructure.jooq.tables.Commodity;
import org.example.infrastructure.jooq.tables.Promotion;
import org.example.infrastructure.jooq.tables.User;


/**
 * Convenience access to all tables in ecom-plat.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ecom-plat.commodity</code>.
     */
    public static final Commodity COMMODITY = Commodity.COMMODITY;

    /**
     * The table <code>ecom-plat.promotion</code>.
     */
    public static final Promotion PROMOTION = Promotion.PROMOTION;

    /**
     * The table <code>ecom-plat.user</code>.
     */
    public static final User USER = User.USER;
}
